version: "3.9"

services:
  backend:
    restart: unless-stopped
    build:
      context: .
    image: intern_stats
    command: sh -c /app/entrypoint.prod
    container_name: intern_stats
    volumes:
        - "./db.sqlite3:/app/db.sqlite3"
    ports:
      - "127.0.0.1:8011:8000"
    env_file:
      - .env.prod
    environment:
    - PYTHONUNBUFFERED=1