# Generated by Django 3.0.7 on 2023-07-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year_placed',
            field=models.CharField(choices=[('2023', '2023'), ('2022', '2022')], default='', max_length=4),
        ),
        migrations.AlterField(
            model_name='branch',
            name='branchName',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='slot',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
